server:
  port: 8011

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/
